a= input('Digite algo:')
print (type(a))
print ('é um numero', a.isnumeric())
print ('É alfabetico', a.isalpha())
print ('Isso é alfanumerico', a.isalnum())
print ('Contem somente espaços:', a.isspace())
print ('Está em letras maiusculas', a.isupper())
print ('Está em letras minusculas', a.islower())
print ('Está capitalizada', a.istitle())